export const TASK_TYPES = {
    EXPORT_BOOK: 'EXPORT_BOOK',
    WEB_BOOK_COLLECT: 'WEB_BOOK_COLLECT',
};

export const TASK_MESSAGE_TYPE = {
    TASK_ERROR: "TASK_ERROR",
    TASK_COMPLETED: "TASK_COMPLETED",
};
